# Generated by Django 3.0.8 on 2020-07-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='name',
            new_name='survey_name',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='survey_participants',
        ),
        migrations.AddField(
            model_name='survey',
            name='sp_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='surveyparticipant',
            field=models.CharField(default='Adwoa Tay', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='survey',
            table='survey',
        ),
    ]
