# Generated by Django 2.2.2 on 2020-07-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_surveyquestions_survey_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestions',
            name='survey_id',
            field=models.IntegerField(),
        ),
    ]
