# Generated by Django 2.2.2 on 2020-07-31 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
