# Generated by Django 2.2.2 on 2020-08-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_delete_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='option_one_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='option_three_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='option_two_count',
            field=models.IntegerField(default=0),
        ),
    ]
