# Generated by Django 2.2.2 on 2020-08-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20200801_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='option_one',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option_one_count',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option_three',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option_three_count',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option_two',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option_two_count',
        ),
        migrations.AddField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('text', 'text'), ('radio', 'radio'), ('select', 'select'), ('select-multiple', 'Select Multiple'), ('integer', 'integer')], default='text', max_length=200),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(max_length=64),
        ),
    ]
